### ISSUE TITLE
you did not make this code

### ISSUE THREAD

**Issue by Liam3452** [raunvk/stealthware-backdoor#1]
Hey how about you give credit to the course you did to make this malware, https://www.udemy.com/course/build-undetectable-malware-using-c-language-ethical-hacking/ you did not make it, I did the same course to and at least I give credit to the creator and if you are going to build your own malware make a original one like I am currently doing, not copying and pasting a code from a course and saying its yours, skid

**Comment by raunvk** [comment]
Sure, I'll give the credit in README.md of the repo. Will that be ok?
It was a mistake from my side to overlook that part, I should have given credit earlier.
I don't intend to steal/plagiarise or promote it as my work. It was just a personal project.

**Comment by Liam3452** [comment]
ok good
