### ISSUE TITLE
Abt keylogging & persistency

### ISSUE THREAD

**Issue by ekmekovski** [raunvk/stealthware-backdoor#2]
I connected to the victim machine but when I use keylog_start and persist command nothing was happened I also check the registries and I cannot find anything, what I tried to ask is these features are working or I could not make it work? Thnk u for this repo btw it is fun.

**Comment by raunvk** [comment]
Hi,
I'm glad you enjoyed recreating the project.
I think you are facing such a problem because your machine and the target
machine are not on the same network.
For the backdoor to work, you have to connect with a machine that is on the
same network.
Hope this helps.
